server:
  port: 9000

grpc:
  server:
    port: 9090

db:
  my_db:
    url: jdbc:mysql://localhost:13306/my_db
    username: admin
    password: 123456

tos:
  secretId: mock
  secretKey: mock
  bucket: mock
  region: mock
  cdnHost: obj-storage-1304785445.shiqihao.xyz

redis:
  host: localhost
  port: 16379
  password: 123456

jwtSecretKey: BObrNLDYrarBp_miPwmzrDEgDYOENB1uYJ702R143wI
